config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins, skip: [:registrations]

  # needs to be AFTER "devise_for :admins" otherwise the admin routes will be messed up
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :signup_onboarding

  authenticate :user do
    resources :training_stations, path: '/training-stations', only: [:index, :show] do
      resources :quizzes, path: '/tests', only: [:index, :show]
    end

    resources :learning_modules, path: '/learning-modules', only: [:index]
    get '/payroll' => 'payroll#index'
    scope :pages do
      get 'our-philosophy' => 'pages#our_philosophy'
      get 'certification' => 'pages#certification'
    end
  end

  authenticated :user do
    root to: 'pages#dashboard', as: :authenticated_root
  end

  root 'visitors#index'
end

app/controllers/visitors_controller.rb
# frozen_string_literal: true
class VisitorsController < ApplicationController
end

app/views/visitors/index.html.haml
.container
  .row
    .col-md-offset-4.col-md-4.text-center
      .login-container
        = image_tag 'crave_logo', class: 'img-responsive logo'
        %p "Excellence is an art won by training and habituation. We do not act rightly because we have virtue or excellence, but we rather have those because we have acted rightly. We are what we repeatedly do. Excellence, then, is not an act but a habit." Aristotle
        - unless current_user
          .btn-container
            = link_to 'Sign Up', signup_onboarding_path(:confirm_name), class: 'btn btn-primary'
            = link_to 'Log In', new_user_session_path, class: 'btn btn-success'