config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins, skip: [:registrations]

  # needs to be AFTER "devise_for :admins" otherwise the admin routes will be messed up
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :signup_onboarding

  authenticate :user do
    resources :training_stations, path: '/training-stations', only: [:index, :show] do
      resources :quizzes, path: '/tests', only: [:index, :show]
    end

    resources :learning_modules, path: '/learning-modules', only: [:index]
    get '/payroll' => 'payroll#index'
    scope :pages do
      get 'our-philosophy' => 'pages#our_philosophy'
      get 'certification' => 'pages#certification'
    end
  end

  authenticated :user do
    root to: 'pages#dashboard', as: :authenticated_root
  end

  root 'visitors#index'
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{ class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}" }
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar
  .nav-block
    - if user_signed_in?
      .hamburger-icon
        %span
        %span
        %span
        %span
      = link_to 'Performance Reviews', '#', class: 'navbar-link'
      = link_to 'My Account', edit_user_registration_path, class: 'navbar-link'
      = link_to 'Sign Out', destroy_user_session_path, method: :delete

    - else
      .crave-logo
        = link_to root_path, class: 'navbar-logo' do
          = image_tag 'crave_logo', class: 'img-responsive', width: '100px'
      = link_to 'Sign In', new_user_session_path, class: 'navbar-link'

app/views/layouts/_sidebar.html.haml
%ul.sidebar-nav.text-uppercase
  %li.sidebar-brand
    = link_to root_path do
      = image_tag 'crave_logo', class: 'img-responsive sidebar-logo'
  %li.sidebar-item
    = link_to 'Inbox', '#', class: 'navbar-brand'
  %li.sidebar-item
    = link_to 'My Training', training_stations_path, class: 'navbar-brand'
  %li.sidebar-item
    = link_to 'Certification', certification_path, class: 'navbar-brand'
  %li.sidebar-item
    = link_to 'Schedule', '#', class: 'navbar-brand'
  %li.sidebar-item
    = link_to 'Our Philosophy', our_philosophy_path, class: 'navbar-brand'
  %li.sidebar-item
    = link_to 'Payroll', payroll_path, class: 'navbar-brand'
  %li.sidebar-item
    = link_to 'Learning Centre', learning_modules_path, class: 'navbar-brand'
  %li.sidebar-item
    = link_to 'Legends', '#', class: 'navbar-brand'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
    %title= content_for?(:title) ? yield(:title) : 'Crave Employee Portal'
    %meta{ name: 'description', content: (content_for?(:description) ? yield(:description) : 'Crave Employee Portal').to_s }
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{ class:  "#{controller_path.tr('_', '-').tr('/', '-')} #{action_name.tr('_', '-')}" }
    .wrapper
      %main{ role: 'main' }
        - if user_signed_in?
          .sidebar
            = render 'layouts/sidebar'
        = render 'layouts/messages'
        = render 'layouts/navigation'
        .content
          = yield